# header social icons
twitter: acnilburgos               
instagram: acnilburgos           
github: acnil
test: false


# home page profile
# avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
# name = 'YOUR_NAME'
# bio = 'YOUR_BIO'


# misc
monoDarkIcon: true                     # show monochrome dark mode icon


# oidc:
  # clientID: 394665744425-m05sdc1tarsm5knfrcv5jnd33o18ish7.apps.googleusercontent.com
  # clientSecret: 
  # CryptoPassphrase: Not-Set 